name: Update Game Projects

on:
  push:
    branches:
      - main

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GunduzTech
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "frkngndz60@gmail.com"
          git config --global user.name "dgdfurkan"

      - name: Get all repositories
        id: get_repos
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          REPO_LIST=$(curl -s -H "Authorization: token ${GH_PAT}" "https://api.github.com/user/repos?per_page=100&affiliation=owner" | jq -r '.[] | select(.default_branch and .default_branch == "main") | .name')
          echo "REPO_LIST=$(echo "$REPO_LIST" | tr ' ' '\n' | awk '!seen[$0]++' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Filter only GunduzTech-based projects
        run: |
          FINAL_REPOS=""
          for repo in $REPO_LIST
          do
            if curl -s -H "Authorization: token ${GH_PAT}" "https://raw.githubusercontent.com/dgdfurkan/$repo/main/GunduzTech/.gunduztech" | grep -q "GunduzTech"; then
              FINAL_REPOS="$FINAL_REPOS $repo"
            fi
          done
          echo "FINAL_REPOS=$FINAL_REPOS" >> $GITHUB_ENV

      - name: Update all GunduzTech-based projects
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          for repo in $FINAL_REPOS
          do
            git clone https://${GH_PAT}@github.com/dgdfurkan/$repo.git
            cd $repo
            
            git checkout main
            git pull origin main
            
            git subtree pull --prefix=GunduzTech git@github.com:dgdfurkan/GunduzTech.git main --squash
            
            git add .
            git commit -m "Auto-update GunduzTech" || echo "No changes to commit"
            git push origin main
            
            cd ..
          done
